/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PatientRecord = IDL.Record({
  'bloodType' : IDL.Text,
  'owner' : IDL.Principal,
  'patientId' : IDL.Text,
  'encryptedNotes' : IDL.Text,
  'createdAt' : IDL.Int,
  'encryptedAge' : IDL.Text,
  'emergencyPhone' : IDL.Text,
  'encryptedEmergencyContact' : IDL.Text,
  'encryptedName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(PatientRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPatients' : IDL.Func([], [IDL.Vec(PatientRecord)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PatientRecord = IDL.Record({
    'bloodType' : IDL.Text,
    'owner' : IDL.Principal,
    'patientId' : IDL.Text,
    'encryptedNotes' : IDL.Text,
    'createdAt' : IDL.Int,
    'encryptedAge' : IDL.Text,
    'emergencyPhone' : IDL.Text,
    'encryptedEmergencyContact' : IDL.Text,
    'encryptedName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(PatientRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPatients' : IDL.Func([], [IDL.Vec(PatientRecord)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };